import React from 'react';
import { useAuth } from '../context/AuthContext';

interface ReportHeaderProps {
  reportName: string;
  storeName: string;
  period: string; // e.g., "01 Aug 2026 - 31 Aug 2026"
}

export const ReportHeader: React.FC<ReportHeaderProps> = ({ reportName, storeName, period }) => {
  const { profile } = useAuth();
  const generatedDate = new Date().toLocaleDateString('en-KE', { day: 'numeric', month: 'short', year: 'numeric' });
  const generatedBy = profile?.name || profile?.email || 'Unknown';
  return (
    <div className="border-b border-gray-200 pb-4 mb-4">
      <h1 className="text-2xl font-extrabold text-gray-900">{reportName}</h1>
      <div className="mt-2 text-sm text-gray-600">
        <p><strong>Store:</strong> {storeName}</p>
        <p><strong>Report Period:</strong> {period}</p>
        <p><strong>Generated Date:</strong> {generatedDate}</p>
        <p><strong>Generated By:</strong> {generatedBy}</p>
      </div>
    </div>
  );
};
